# Generated by Django 2.2.2 on 2019-06-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gg', '0002_auto_20190630_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='linksrecuperacao',
            name='data2',
            field=models.TimeField(auto_now=True),
        ),
    ]
