# Generated by Django 2.2.2 on 2019-06-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gg', '0004_remove_linksrecuperacao_data2'),
    ]

    operations = [
        migrations.AddField(
            model_name='linksrecuperacao',
            name='status',
            field=models.BooleanField(default=1),
        ),
    ]
